[formatting]
align_comments = true
align_entries = false
array_auto_expand = true
array_trailing_comma = true
column_width = 100
indent_string = "    "
inline_table_expand = false
reorder_keys = true
